# Generated by Django 5.0.4 on 2024-05-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='subject',
            new_name='Subject',
        ),
    ]
