# Generated by Django 5.0.4 on 2025-02-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_message_contactdb_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('Password', models.CharField(blank=True, max_length=500, null=True)),
                ('Confirmpassword', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
