# Generated by Django 5.0.4 on 2025-03-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(blank=True, max_length=500, null=True)),
                ('Pname', models.CharField(blank=True, max_length=500, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
