# Generated by Django 5.0.4 on 2025-03-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oname', models.CharField(blank=True, max_length=500, null=True)),
                ('Oemail', models.EmailField(blank=True, max_length=500, null=True)),
                ('Oaddress', models.CharField(blank=True, max_length=500, null=True)),
                ('Omobile', models.IntegerField(blank=True, null=True)),
                ('Ototalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
